name: tautulli
adopt-info: tautulli
summary: A Python based monitoring and tracking tool for Plex Media Server.
description: >
  Tautulli is a 3rd party application that you can run alongside your Plex Media Server to monitor activity and track various statistics. 
  Most importantly, these statistics include what has been watched, who watched it, when and where they watched it, and how it was watched. 
  The only thing missing is "why they watched it", but who am I to question your 42 plays of Frozen. 
  All statistics are presented in a nice and clean interface with many tables and graphs, which makes it easy to brag about your server to everyone else.

base: core22
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

parts:
  tautulli:
    plugin: dump
    source: .
    stage-packages:
      - python3
      - python3-openssl
      - python3-pycryptodome
      - python3-setuptools
      - python3-pkg-resources
    build-packages:
      - git
      - python3
      - python3-openssl
      - python3-pycryptodome
      - python3-setuptools
      - python3-pkg-resources
    override-pull: |
      snapcraftctl pull
      git config --global --add safe.directory /data/parts/tautulli/src
      echo "$(git describe --tag)"
      # TAG_FULL=$(git describe --tag)
      # echo $TAG_FULL
      TAG_FULL=v2.11.0-11-g609f59d5
      # TAG=$(echo $TAG_FULL | grep -oP '(v\d+\.\d+\.\d+(?>-beta)?)')
      # echo $TAG
      TAG=v2.11.0
      # BRANCH=$(git rev-parse --abbrev-ref HEAD)
      # echo $BRANCH
      BRANCH=nightly
      # COMMIT=$(git rev-parse HEAD)
      # echo $COMMIT
      COMMIT=4d6cb2e18bb1e6da932827621a6b3e5547c53132
      if [ "$TAG" = "$TAG_FULL" ]; then
        VERSION=$TAG
      else
        VERSION=$(echo $COMMIT | head -c 7)
      fi
      echo $VERSION
      if [ ! "$VERSION" = "$TAG" ] || [ ! "$VERSION" = "${VERSION%-beta}" ]; then
        GRADE=devel
      else
        GRADE=stable
      fi
      echo $GRADE
      if [ "$VERSION" = "$TAG" ] && [ ! "$VERSION" = "${VERSION%-beta}" ]; then
        BRANCH=beta
      elif [ "$VERSION" = "$TAG" ]; then
        BRANCH=master
      fi
      echo $BRANCH
      echo $BRANCH > branch.txt
      echo $COMMIT > version.txt
      snapcraftctl set-version "$VERSION"
      snapcraftctl set-grade "$GRADE"
    override-prime: |
      snapcraftctl prime
      mkdir -p usr/bin
      ln -s /usr/bin/python3 usr/bin/python3

apps:
  tautulli:
    command: usr/bin/python3 $SNAP/Tautulli.py --datadir $SNAP_USER_COMMON/Tautulli --config $SNAP_USER_COMMON/Tautulli/config.ini --quiet --nolaunch
    daemon: simple
    restart-condition: on-abnormal
    restart-delay: 5s
    plugs:
      - home
      - network
      - network-bind
      - removable-media
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$PYTHONPATH
      TAUTULLI_SNAP: "True"
