name: Pull Requests

on:
  push:
    pull_request: ~

jobs:
  check-branch:
    name: Check Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Comment on Pull Request
        uses: mshick/add-pr-comment@v1
        if: github.base_ref != 'refs/heads/nightly'
        with:
          message: Pull requests must be made to the `nightly` branch. Thanks.
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'

      - name: Fail Workflow
        if: github.base_ref != 'refs/heads/nightly'
        run: |
          echo ${{ github.head_ref }}
          echo ${{ github.base_ref }}
          exit 1
